### ISSUE TITLE
Bug in Ubuntu network.sh script causes kernel upgrades to fail for Ubuntu 16.04

### ISSUE THREAD

**Issue by evancox10** [taliesins/packer-baseboxes#4]
Hello, the part of your network.sh script for ubuntu that tries to disable udev persistent net rules causes some undesirable side effects. If you make /etc/udev/rules.d/70-persistent-net.rules a directory, then some very low-level scripts used by the kernel update process for the linux-firmware and update-initramfs will fail. 

(The script that fails is /usr/share/initramfs-tools/hooks/udev. It performs a cp on files in the /etc/udev/rules.d/ folder. Since there is now a directory here, that copy will fail, causing the script to break.)

I'm not sure what the "right" way is to disable persistent net rules, this method may work but has a big downside!

**Comment by evancox10** [comment]
FYI: https://github.com/chef/bento/issues/592

**Comment by evancox10** [comment]
This only applies to Ubuntu 15.10 or later VMs; which for this repo means the 16.04 image. For these releases, Ubuntu has moved to "[Predictable Network Interface Names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/)". Therefore, persistent net rules is no longer used and we don't even need to hack around it in the first place. The "fix" implemented by the chef/bento team in the issue linked to below is to just not perform the empty directory hack in the first place. Note that this doesn't mean you automatically go back to the good ol' eth0/eth1/etc. network interface names! If you want these old names, you will have to implement a fix like described [here](http://askubuntu.com/a/788343). (Warning, fix untested, use at your own risk!)


P.S. Thanks for the work on this repo and the Packer + Hyper-V code. I am up and running with this now, and obviously playing around with it now trying to get a feel for things. I really appreciate your contributions that have allowed this to happen!

**Comment by taliesins** [comment]
Thanks for the kind words.

Send me a pull request for the fix, if it sorted you out ;)

**Comment by taliesins** [comment]
@evancox10 went the Bento route
