### ISSUE TITLE
Vmware/VSphere.

### ISSUE THREAD

**Issue by rismoney** [taliesins/packer-baseboxes#5]
Can you clarify the difference between these and when each should be used:

Vmware
VSphere via Vmware
VSphere directly

**Comment by taliesins** [comment]
vmware-* is Vmware Workstation
vsphere-* is build it locally on Vmware Workstation then upload virtual machine to VSphere
vsphere-remote-* is build it on VSphere (this is normally the one to go for, as it normally has the best resources available. I can do 8 in parallel for example)
