### ISSUE TITLE
The hyperv boxes are not getting an ip address

### ISSUE THREAD

**Issue by marcofranssen** [taliesins/packer-baseboxes#6]
I tr the ubuntu 14.04 basebox on hyperv, but it seems to be not getting an ip address automatically.

I'm on latest Windows 10 release.

**Comment by taliesins** [comment]
Do you have DHCP setup somewhere, that your VM has access to?

**Comment by marcofranssen** [comment]
Yes. My laptop itself also receives an ip from the wifi. So that should work right?
